services:
  - type: web
    name: skype-stats-api
    env: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PORT
        value: 10000
    scaling:
      minInstances: 1
      maxInstances: 1
    healthCheckPath: /health
    autoDeploy: false 