services:
  - type: worker
    name: skype-stats
    env: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: SKYPE_USERNAME
        sync: false
      - key: SKYPE_PASSWORD
        sync: false
    plan: starter
    buildCommand: pip install -r requirements.txt && playwright install chromium && playwright install-deps chromium
    startCommand: python skype_reader.py
    scaling:
      minInstances: 1
      maxInstances: 1
    autoDeploy: false 